# Generated by Django 4.2.9 on 2026-04-16 16:39

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('role', models.CharField(choices=[('central_admin', 'מנהל מרכזי'), ('region_boss', 'מנהל אזור'), ('employee', 'עובד')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'משתמש',
                'verbose_name_plural': 'משתמשים',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('male', 'זכר'), ('female', 'נקבה')], max_length=10)),
                ('apartment_type', models.CharField(choices=[('single', 'רווקים'), ('couple', 'זוגות'), ('family', 'משפחה')], max_length=10)),
                ('room_count', models.PositiveIntegerField()),
                ('apartment_capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('inactive_reason', models.CharField(blank=True, choices=[('reserved', 'שמורה'), ('maintenance', 'תחזוקה'), ('renovation', 'שיפוץ'), ('staff_use', 'שימוש מנהלתי'), ('other', 'אחר')], max_length=20)),
            ],
            options={
                'verbose_name': 'דירה',
                'verbose_name_plural': 'דירות',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'מיטה',
                'verbose_name_plural': 'מיטות',
                'ordering': ['room', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('ended', 'הסתיים'), ('cancelled', 'בוטל')], default='active', max_length=20)),
                ('assignment_type', models.CharField(choices=[('initial', 'שיבוץ ראשוני'), ('transfer', 'העברה'), ('manual', 'ידני'), ('phase2', 'שלב 2')], default='manual', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bed_assignments', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.bed')),
            ],
            options={
                'verbose_name': 'שיבוץ מיטה',
                'verbose_name_plural': 'שיבוצי מיטות',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'מעבד'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'קובץ יבוא',
                'verbose_name_plural': 'קבצי יבוא',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('internal', 'מעבר פנימי'), ('region_change', 'מעבר בין אזורים'), ('dorm_type_change', 'שינוי סוג מעונות'), ('phase2', 'שלב 2')], default='internal', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('completed', 'הושלם')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to=settings.AUTH_USER_MODEL)),
                ('from_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_from', to='api.bedassignment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'בקשת תנועה',
                'verbose_name_plural': 'בקשות תנועה',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_type', models.CharField(choices=[('central', 'לשכה מרכזית'), ('regional', 'משרד אזורי')], default='regional', max_length=20)),
            ],
            options={
                'verbose_name': 'משרד',
                'verbose_name_plural': 'משרדים',
                'ordering': ['office_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'אזור',
                'verbose_name_plural': 'אזורים',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.apartment')),
            ],
            options={
                'verbose_name': 'חדר',
                'verbose_name_plural': 'חדרים',
                'ordering': ['apartment', 'name'],
                'unique_together': {('apartment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('business_partner_id', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'זכר'), ('female', 'נקבה')], max_length=10)),
                ('religion', models.CharField(choices=[('secular', 'חילוני'), ('religious', 'דתי'), ('traditional', 'מסורתי'), ('not_specified', 'לא צוין')], default='not_specified', max_length=20)),
                ('nationality', models.CharField(choices=[('israeli', 'ישראלי'), ('international', 'בינלאומי')], default='israeli', max_length=20)),
                ('category', models.CharField(choices=[('new', 'סטודנטים חדשים'), ('continuing', 'ממשיכים'), ('transfer', 'מעברים'), ('leaving', 'עזיבה')], default='new', max_length=20)),
                ('housing_type', models.CharField(blank=True, max_length=100)),
                ('allocation_group', models.CharField(blank=True, max_length=50)),
                ('roommate_request_1', models.CharField(blank=True, max_length=100)),
                ('roommate_request_2', models.CharField(blank=True, max_length=100)),
                ('roommate_request_3', models.CharField(blank=True, max_length=100)),
                ('roommate_request_4', models.CharField(blank=True, max_length=100)),
                ('roommate_request_5', models.CharField(blank=True, max_length=100)),
                ('is_priority', models.BooleanField(default=False)),
                ('priority_reason', models.CharField(blank=True, max_length=255)),
                ('disability_percentage', models.PositiveIntegerField(default=0)),
                ('medical_approval', models.BooleanField(default=False)),
                ('current_address', models.CharField(blank=True, max_length=255)),
                ('current_region_name', models.CharField(blank=True, max_length=100)),
                ('decision_status', models.CharField(blank=True, max_length=50)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.room')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.importbatch')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.region')),
            ],
            options={
                'verbose_name': 'סטודנט',
                'verbose_name_plural': 'סטודנטים',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('movement_type', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='api.room')),
                ('movement_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transfer', to='api.movementrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transfers', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='api.student')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='api.room')),
            ],
            options={
                'verbose_name': 'בקשת העברה',
                'verbose_name_plural': 'בקשות העברה',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('central_admin', 'מנהל מרכזי'), ('region_boss', 'מנהל אזור'), ('employee', 'עובד')], max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='api.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'פרופיל עובד',
                'verbose_name_plural': 'פרופילי עובדים',
            },
        ),
        migrations.CreateModel(
            name='RegionInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('viewed', 'נצפה'), ('processed', 'טופל'), ('superseded', 'הוחלף')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_inboxes', to='api.importbatch')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='api.region')),
            ],
            options={
                'verbose_name': 'הודעת אזור',
                'verbose_name_plural': 'הודעות אזור',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='office',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.region'),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_requests', to='api.student'),
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='to_bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_to', to='api.bed'),
        ),
        migrations.CreateModel(
            name='DormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dorm_types', to='api.region')),
            ],
            options={
                'verbose_name': 'סוג מעון',
                'verbose_name_plural': 'סוגי מעונות',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dorm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='api.dormtype')),
            ],
            options={
                'verbose_name': 'בניין',
                'verbose_name_plural': 'בניינים',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='api.student'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='api.room'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='api.building'),
        ),
        migrations.CreateModel(
            name='AllocationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'רץ'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='running', max_length=20)),
                ('students_processed', models.PositiveIntegerField(default=0)),
                ('successful_assignments', models.PositiveIntegerField(default=0)),
                ('roommate_matches', models.PositiveIntegerField(default=0)),
                ('conflicts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_runs', to='api.region')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הרצת שיבוץ',
                'verbose_name_plural': 'הרצות שיבוץ',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(condition=models.Q(('office_type', 'regional')), fields=('region', 'office_type'), name='unique_regional_office_per_region'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('building', 'number')},
        ),
    ]
