# Generated by Django 4.2.9 on 2026-04-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_region_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='decision_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='disability_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='medical_approval',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='movementrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='accepted_dorm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_students', to='api.dormtype', verbose_name='סוג מעונות אליו התקבל הסטודנט'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_dorm_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='move_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religious',
            field=models.CharField(choices=[('religious', 'דתי'), ('no_preference', 'לא משנה'), ('not_specified', 'לא צוין')], default='not_specified', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='requested_religion',
            field=models.CharField(choices=[('Muslims', 'מוסלמי'), ('Jewish', 'יהודי'), ('Christian', 'נוצרי'), ('Druze', 'דרוזי'), ('not_specified', 'לא צוין')], default='not_specified', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_flag_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_flag_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_flag_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_flag_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_flag_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='special_status_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='special_status_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='special_status_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='special_status_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='study_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='נקודות לימוד'),
        ),
        migrations.AlterField(
            model_name='bedassignment',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.bed'),
        ),
        migrations.AlterField(
            model_name='bedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bed_assignments', to='api.student'),
        ),
        migrations.AlterField(
            model_name='movementrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_requests', to='api.student'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('bed',), name='unique_active_assignment_per_bed'),
        ),
        migrations.AddConstraint(
            model_name='bedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student',), name='unique_active_assignment_per_student'),
        ),
    ]
