# Generated by Django 4.2.9 on 2026-04-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'מיטה',
                'verbose_name_plural': 'מיטות',
                'ordering': ['room', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('ended', 'הסתיים'), ('cancelled', 'בוטל')], default='active', max_length=20)),
                ('assignment_type', models.CharField(choices=[('initial', 'שיבוץ ראשוני'), ('transfer', 'העברה'), ('manual', 'ידני'), ('phase2', 'שלב 2')], default='manual', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bed_assignments', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.bed')),
            ],
            options={
                'verbose_name': 'שיבוץ מיטה',
                'verbose_name_plural': 'שיבוצי מיטות',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'סוג מעונות',
                'verbose_name_plural': 'סוגי מעונות',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('office_type', models.CharField(choices=[('central', 'לשכה מרכזית'), ('regional', 'משרד אזורי')], default='regional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.region')),
            ],
            options={
                'verbose_name': 'משרד',
                'verbose_name_plural': 'משרדים',
                'ordering': ['office_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='movement_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('apartment', 'name')},
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('central_admin', 'מנהל מרכזי'), ('region_boss', 'מנהל אזור'), ('employee', 'עובד')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to='api.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'פרופיל עובד',
                'verbose_name_plural': 'פרופילי עובדים',
            },
        ),
        migrations.CreateModel(
            name='MovementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('internal', 'מעבר פנימי'), ('region_change', 'מעבר בין אזורים'), ('dorm_type_change', 'שינוי סוג מעונות'), ('phase2', 'שלב 2')], default='internal', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('completed', 'הושלם')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_movements', to=settings.AUTH_USER_MODEL)),
                ('from_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_from', to='api.bedassignment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_movements', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_requests', to='api.student')),
                ('to_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_requests_to', to='api.bed')),
            ],
            options={
                'verbose_name': 'בקשת תנועה',
                'verbose_name_plural': 'בקשות תנועה',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_objects', to='api.building')),
            ],
            options={
                'verbose_name': 'קומה',
                'verbose_name_plural': 'קומות',
                'ordering': ['building', 'number'],
            },
        ),
        migrations.AddField(
            model_name='bedassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='api.student'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='api.room'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='dorm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='api.dormtype'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='api.floor'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='movement_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transfer', to='api.movementrequest'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(condition=models.Q(('office_type', 'regional')), fields=('region', 'office_type'), name='unique_regional_office_per_region'),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'label')},
        ),
    ]
