# Generated by Django 4.2.9 on 2026-01-24 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'מעבד'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'קובץ יבוא',
                'verbose_name_plural': 'קבצי יבוא',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roommate_request_id',
            new_name='business_partner_id',
        ),
        migrations.AddField(
            model_name='student',
            name='allocation_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('new', 'סטודנטים חדשים'), ('continuing', 'ממשיכים'), ('transfer', 'מעברים'), ('leaving', 'עזיבה')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='current_region_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='decision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='decision_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='email_secondary',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='housing_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('israeli', 'ישראלי'), ('international', 'בינלאומי')], default='israeli', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('secular', 'חילוני'), ('religious', 'דתי'), ('traditional', 'מסורתי'), ('not_specified', 'לא צוין')], default='not_specified', max_length=20),
        ),
        migrations.CreateModel(
            name='RegionInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('viewed', 'נצפה'), ('processed', 'טופל'), ('superseded', 'הוחלף')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_inboxes', to='api.importbatch')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to='api.region')),
            ],
            options={
                'verbose_name': 'הודעת אזור',
                'verbose_name_plural': 'הודעות אזור',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.importbatch'),
        ),
    ]
