# Generated by Django 4.2.9 on 2026-04-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='placement_sector',
            field=models.CharField(choices=[('jewish', 'יהודי'), ('arab', 'ערבי'), ('other', 'אחר'), ('unknown', 'לא ידוע')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_student_id_1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_student_id_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_student_id_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_student_id_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='roommate_request_student_id_5',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
