# Generated by Django 4.2.9 on 2026-04-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bed_bedassignment_dormtype_office_apartment_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='description',
        ),
        migrations.RemoveField(
            model_name='region',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
