# Generated by Django 4.2.9 on 2026-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_placement_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'apartment', 'name'], 'verbose_name': 'חדר', 'verbose_name_plural': 'חדרים'},
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.building'),
        ),
    ]
