# Generated by Django 4.2.9 on 2026-04-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_office_created_at_remove_region_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='updated_at',
        ),
    ]
