# Generated by Django 4.2.9 on 2026-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='other_description',
            field=models.TextField(blank=True, default='', help_text='Description text for "other" request type'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='same_apartment',
            field=models.BooleanField(blank=True, help_text='For room change: True = same apartment, False = different apartment', null=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='request_type',
            field=models.CharField(choices=[('room', 'שינוי חדר'), ('apartment', 'מעבר מהדירה'), ('other', 'בקשה אחרת')], max_length=20),
        ),
    ]
