# Generated by Django 4.2.9 on 2026-06-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_options_room_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['dorm_type', 'number'], 'verbose_name': 'בניין', 'verbose_name_plural': 'בניינים'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['apartment', 'name'], 'verbose_name': 'חדר', 'verbose_name_plural': 'חדרים'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='building',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('single', 'רווקים/ות'), ('couple', 'זוגות'), ('family', 'משפחה')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.CharField(choices=[('male', 'זכר'), ('female', 'נקבה'), ('mixed', 'מעורב / לא רלוונטי')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('רווקים', 'רווקים'), ('רווקות', 'רווקות'), ('זוגות', 'זוגות'), ('משפחות עד 2 ילדים (כולל)', 'משפחות עד 2 ילדים (כולל)'), ('רווקים/ות בדירה', 'רווקים/ות בדירה')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('dorm_type', 'number'), name='unique_building_per_dorm_type'),
        ),
    ]
