# Generated by Django 4.2.9 on 2026-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_building_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'זכר'), ('female', 'נקבה')], max_length=10, null=True),
        ),
    ]
