# Generated by Django 4.2.9 on 2026-06-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentrequest_other_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='removal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='removal_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='target_room',
            field=models.ForeignKey(blank=True, help_text='For add student request: room selected during approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests_target_room', to='api.room'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='request_type',
            field=models.CharField(choices=[('add_student', 'הוספת סטודנט'), ('remove_student', 'הסרת סטודנט מהמעונות'), ('room', 'שינוי חדר'), ('apartment', 'מעבר מהדירה'), ('other', 'בקשה אחרת')], max_length=20),
        ),
    ]
