# Generated by Django 4.2.9 on 2026-04-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_current_region_name_and_more'),
        ('api', '0004_remove_staffprofile_created_at_and_more'),
    ]

    operations = [
    ]
