# Generated by Django 4.2.9 on 2026-06-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentrequest_removal_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='student_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='api.student'),
        ),
    ]
