# Generated by Django 4.2.9 on 2026-06-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_studentrequest_student_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
