# Generated by Django 4.2.9 on 2026-06-28 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_gender'),
        ('api', '0007_studentrequest_priority_and_more'),
    ]

    operations = [
    ]
