# Generated by Django 4.2.9 on 2026-06-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_allocationrun_lifecycle_bedassignment_run_fk'),
        ('api', '0008_merge_20260628_2306'),
    ]

    operations = [
    ]
