# Generated by Django 4.2.9 on 2026-07-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260629_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accessibility_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='אחוז נכות'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
