# Generated by Django 4.2.9 on 2026-07-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20260629_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='current_assignment_snapshot',
            field=models.JSONField(blank=True, help_text="Snapshot of the student's bed assignment at request-creation time", null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='destination_regions',
            field=models.ManyToManyField(blank=True, help_text='For cross-region transfers: destination regions selected by the central admin', related_name='destination_transfer_requests', to='api.region'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='final_assignment',
            field=models.ForeignKey(blank=True, help_text='The bed assignment actually created when this request was approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_requests', to='api.bedassignment'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='source_region',
            field=models.ForeignKey(blank=True, help_text="Snapshot of the student's region at request-creation time", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfer_requests', to='api.region'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='swap_with_student',
            field=models.ForeignKey(blank=True, help_text='For swap requests: the other student whose room/bed is being swapped', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_as_partner', to='api.student'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='target_region',
            field=models.ForeignKey(blank=True, help_text='For region_transfer requests: the destination region', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer_requests', to='api.region'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='transfer_scope',
            field=models.CharField(blank=True, choices=[('same_region', 'מעבר בתוך האזור הנוכחי'), ('cross_region', 'מעבר לאזור אחר')], help_text="For room/apartment transfer requests: whether the move stays inside the student's current region or crosses regions", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='request_type',
            field=models.CharField(choices=[('add_student', 'הוספת סטודנט'), ('remove_student', 'הסרת סטודנט מהמעונות'), ('room', 'שינוי חדר'), ('apartment', 'מעבר מהדירה'), ('swap', 'חילוף בין סטודנטים'), ('region_transfer', 'העברה בין אזורים'), ('other', 'בקשה אחרת')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['status', '-created_at'], name='api_student_status_39bcee_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrequest',
            index=models.Index(fields=['request_type'], name='api_student_request_56f37b_idx'),
        ),
    ]
