# Generated by Django 4.2.9 on 2026-07-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_accessibility_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='gender_restriction',
            field=models.CharField(blank=True, choices=[('male', 'בנים בלבד'), ('female', 'בנות בלבד')], help_text='לבניינים עם שירותים משותפים: כל הבניין מוגבל למגדר אחד, ללא קשר לקטגוריית הדירות. ריק = ללא הגבלת בניין (ברירת מחדל).', max_length=10, verbose_name='הגבלת מגדר לבניין'),
        ),
    ]
