# Generated by Django 4.2.9 on 2026-07-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_studentrequest_current_assignment_snapshot_and_more'),
        ('api', '0011_building_gender_restriction'),
    ]

    operations = [
    ]
