# Generated by Django 4.2.9 on 2026-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260714_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='diagnostics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
