# Generated by Django 4.2.9 on 2026-08-09 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_allocationrun_diagnostics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistedAllocationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('manual_assignment', 'שיבוץ ידני'), ('manual_override', 'שיבוץ בחריגה'), ('config_change', 'שינוי הגדרת דירה/בניין')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('overridden_rules', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_allocation_actions', to=settings.AUTH_USER_MODEL)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_allocation_audit_entries', to='api.apartment')),
                ('bed_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_allocation_audit_entries', to='api.bedassignment')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_allocation_audit_entries', to='api.building')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_allocation_actions', to='api.student')),
            ],
            options={
                'verbose_name': 'פעולת שיבוץ מסייע',
                'verbose_name_plural': 'פעולות שיבוץ מסייע',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='api_assiste_student_004ea6_idx'), models.Index(fields=['action_type', '-created_at'], name='api_assiste_action__2b1875_idx')],
            },
        ),
    ]
