# Generated by Django 4.2.9 on 2026-08-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_assistedallocationaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='live_snapshot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='allocationrun',
            name='max_search_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocationrun',
            name='status',
            field=models.CharField(choices=[('queued', 'בתור'), ('running', 'רץ'), ('cancellation_requested', 'מבוקשת עצירה'), ('stop_and_save_requested', 'מבוקשת עצירה ושמירה'), ('stopped', 'עצר'), ('completed', 'הושלם'), ('failed', 'נכשל'), ('deleted', 'נמחק'), ('approved', 'אושר')], default='queued', max_length=30),
        ),
    ]
