# Generated by Django 4.2.9 on 2026-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_allocationrun_live_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrun',
            name='search_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
