# Generated by Django 4.2.9 on 2026-08-13 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_allocationrun_search_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('main', 'קובץ שיבוץ ראשי'), ('additions', 'קובץ מתווספים')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='processed_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='total_rows',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='created_in_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to='api.importbatch'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין להעלאה'), ('processing', 'מעבד'), ('cancellation_requested', 'בקשת עצירה'), ('stop_and_delete_requested', 'בקשת עצירה ומחיקה'), ('stopped', 'נעצר'), ('completed', 'הושלם'), ('failed', 'נכשל')], default='pending', max_length=30),
        ),
    ]
