# Generated by Django 4.2.9 on 2026-08-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_importbatch_finished_at_importbatch_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('approved', 'אושר'), ('rejected', 'נדחה'), ('cancelled', 'בוטל')], default='pending', max_length=20),
        ),
    ]
