# Generated by Django 4.2.9 on 2026-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_studentrequest_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'region_boss')), fields=('region',), name='unique_region_boss_per_region'),
        ),
    ]
