*
!package.json
!package-lock.json
!npm-shrinkwrap.json
!yarn.lock

!src
!src/**

!public
!public/**

!Dockerfile.frontend

!jsconfig.json
!tsconfig.json
!craco.config.js
!vite.config.js
!vite.config.ts
!postcss.config.js
!tailwind.config.js
