"""
Group 2 — Concurrency & Load audit: load/throughput measurements.

WHY LiveServerTestCase, NOT TestCase/TransactionTestCase + APIClient:
Section 7 of the audit (connection/resource behavior) specifically needs
to observe REAL Django development-server behavior under concurrent HTTP
traffic - a real accept()/thread-per-request cycle, real sockets, real
per-request Postgres connections (CONN_MAX_AGE=0, see settings.py) - none
of which APIClient exercises (it calls the view function in-process,
never opening a socket or going through WSGI). LiveServerTestCase starts
an actual threaded WSGI server on a real local port; the `requests`
library is used as a genuine, independent HTTP client hitting it, exactly
like a browser or the real frontend would.

Authentication uses a real JWT access token (obtained once via
RefreshToken.for_user(), not by hitting the login endpoint under load -
login throughput is not what this module measures) sent as a normal
Authorization header on every request, exactly as the real frontend does.

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.concurrency_tests.test_load_concurrency -v 2
"""

import statistics
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests
from django.conf import settings
from django.test import LiveServerTestCase
from rest_framework_simplejwt.tokens import RefreshToken

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment, StudentRequest,
)

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'concurrency' / 'evidence'
# AFTER-FIX evidence file - the audit's own evidence/GROUP2_LOAD_MEASUREMENTS.txt
# is preserved unmodified as the "before" record (see
# GROUP2_CONCURRENCY_LOAD_IMPLEMENTATION_REPORT.md §9 for the comparison).
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP2_LOAD_MEASUREMENTS_AFTER_FIX.txt'
_evidence_lines = []

CONCURRENCY_LEVELS = (1, 5, 10, 20)


def _record(*lines):
    _evidence_lines.extend(lines)
    for line in lines:
        print(line)


def _flush_evidence():
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(_evidence_lines) + '\n')


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


def _token_for(user):
    return str(RefreshToken.for_user(user).access_token)


class LoadConcurrencyTests(LiveServerTestCase):
    """
    Seeds a modest, realistic dataset (a handful of buildings/rooms/beds,
    ~20 students, ~10 pending requests - comparable in scale to Group 1's
    performance-test fixtures, not an artificial mega-dataset) once for
    the whole class, then fires CONCURRENCY_LEVELS-many simultaneous real
    HTTP GET requests at a representative set of endpoints, measuring
    success/failure counts, latency distribution, and total throughput at
    each level.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        _record(
            'Group 2 load/throughput measurements (AFTER row-locking fixes) - GET endpoints under '
            'concurrent real HTTP load',
            'Generated by backend/api/concurrency_tests/test_load_concurrency.py',
            'Re-run after the Group 2 implementation phase (StudentRequest/Transfer row locking) to '
            'confirm no read-endpoint regression - compare against the audit baseline in '
            'evidence/GROUP2_LOAD_MEASUREMENTS.txt.',
            f'Concurrency levels measured: {CONCURRENCY_LEVELS}',
            'Server: Django LiveServerTestCase (real threaded WSGI dev server, real sockets, '
            'real per-request DB connections - CONN_MAX_AGE=0, matching production settings.py). '
            'Uses 127.0.0.1 explicitly (not "localhost") to avoid the Windows DNS/connect artifact '
            'diagnosed in the audit.',
            '',
        )

    @classmethod
    def tearDownClass(cls):
        _flush_evidence()
        super().tearDownClass()

    def setUp(self):
        # NOTE: fixtures are (re)built per-test-method, not once in
        # setUpClass(). LiveServerTestCase inherits TransactionTestCase's
        # per-test table truncation (_fixture_teardown()) - data created
        # once in setUpClass() would be wiped after the FIRST test method
        # runs, leaving every subsequent test measuring against an
        # increasingly empty (and misleadingly fast) database. This
        # mirrors the setUp()-per-test convention used throughout this
        # whole project's TransactionTestCase-based tests.
        self.region = Region.objects.create(id='g2-load-region', name='G2 Load Region')
        self.dorm_type = DormType.objects.create(code=9100, name='G2LoadDormType', region=self.region)
        self.admin = _make_user('g2-load-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.token = _token_for(self.admin)

        rooms = []
        for b in range(3):
            building = Building.objects.create(number=100 + b, dorm_type=self.dorm_type)
            apartment = Apartment.objects.create(
                building=building, number='1', category=Apartment.Category.MIXED,
                apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
            )
            for r in range(2):
                room = Room.objects.create(apartment=apartment, name=str(r + 1), capacity=4)
                for bed_i in range(4):
                    Bed.objects.create(room=room, label=f'B{bed_i}')
                rooms.append(room)

        students = []
        for i in range(20):
            student = Student.objects.create(
                student_id=f'LOAD-{i}', first_name='F', last_name='L',
                gender='male' if i % 2 == 0 else 'female',
                housing_type=(
                    Student.HousingType.SINGLE_MALE if i % 2 == 0 else Student.HousingType.SINGLE_FEMALE
                ),
                accepted_dorm_type=self.dorm_type,
            )
            students.append(student)
            if i < 12:
                room = rooms[i % len(rooms)]
                bed = Bed.objects.filter(room=room)[i % 4]
                BedAssignment.objects.create(
                    student=student, bed=bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
                )

        for i in range(10):
            StudentRequest.objects.create(
                request_type=StudentRequest.RequestType.OTHER, reason=f'load-{i}',
                requested_by=self.admin, student=students[i],
            )

    def _headers(self):
        return {'Authorization': f'Bearer {self.token}'}

    def _measure(self, label, url, n):
        """
        Fires n concurrent GET requests at `url` and returns a dict of
        measurements: success/failure counts, latency stats (ms), total
        wall-clock time, and simple throughput (requests/sec).
        """
        def _one():
            start = time.perf_counter()
            try:
                resp = requests.get(url, headers=self._headers(), timeout=30)
                elapsed_ms = (time.perf_counter() - start) * 1000
                return resp.status_code, elapsed_ms, None
            except requests.RequestException as exc:
                elapsed_ms = (time.perf_counter() - start) * 1000
                return None, elapsed_ms, str(exc)

        wall_start = time.perf_counter()
        with ThreadPoolExecutor(max_workers=n) as pool:
            results = list(pool.map(lambda _: _one(), range(n)))
        wall_elapsed_s = time.perf_counter() - wall_start

        statuses = [r[0] for r in results]
        latencies = [r[1] for r in results]
        exceptions = [r[2] for r in results if r[2]]
        success = sum(1 for s in statuses if s == 200)
        failure = n - success

        stats = {
            'label': label, 'concurrency': n, 'success': success, 'failure': failure,
            'exceptions': exceptions,
            'latency_min_ms': min(latencies), 'latency_max_ms': max(latencies),
            'latency_mean_ms': statistics.mean(latencies),
            'latency_p95_ms': (
                statistics.quantiles(latencies, n=20)[18] if len(latencies) >= 5 else max(latencies)
            ),
            'wall_clock_s': wall_elapsed_s,
            'throughput_req_per_s': n / wall_elapsed_s if wall_elapsed_s > 0 else float('inf'),
        }

        line = (
            f'{label:28s} N={n:<3d} success={success:<3d} failure={failure:<3d} '
            f'latency_ms[min={stats["latency_min_ms"]:.1f} mean={stats["latency_mean_ms"]:.1f} '
            f'p95={stats["latency_p95_ms"]:.1f} max={stats["latency_max_ms"]:.1f}] '
            f'wall_s={stats["wall_clock_s"]:.3f} throughput_req_s={stats["throughput_req_per_s"]:.1f}'
        )
        _record(line)
        if exceptions:
            _record(f'    exceptions ({len(exceptions)}): {exceptions[:3]}')
        return stats

    def _measure_across_levels(self, label, path):
        # IMPORTANT (itself a documented finding - see audit report §7):
        # self.live_server_url is "http://localhost:<port>". Resolving/
        # connecting to the literal hostname "localhost" on this Windows
        # machine takes ~2000ms per TCP connect (confirmed directly: a raw
        # socket.create_connection(('localhost', port)) took ~2020ms vs
        # ~13ms for socket.create_connection(('127.0.0.1', port)) against
        # the exact same listening server) - a well-known Windows
        # IPv6-then-IPv4-fallback DNS/connect quirk, entirely a local
        # environment artifact with zero relation to Django or this
        # backend's code. Using 127.0.0.1 explicitly here removes that
        # ~2s-per-request local artifact so the measurements below reflect
        # actual request processing time, not localhost resolution.
        url = self.live_server_url.replace('localhost', '127.0.0.1') + path
        all_stats = []
        for n in CONCURRENCY_LEVELS:
            all_stats.append(self._measure(label, url, n))
        return all_stats

    def test_home_dashboard_load(self):
        _record('--- GET /api/home/ (operational dashboard) ---')
        stats = self._measure_across_levels('home_dashboard', '/api/home/')
        self._assert_no_pathological_degradation(stats)

    def test_students_list_load(self):
        _record('--- GET /api/students/ ---')
        stats = self._measure_across_levels('students_list', '/api/students/?page_size=50')
        self._assert_no_pathological_degradation(stats)

    def test_requests_list_load(self):
        _record('--- GET /api/requests/ ---')
        stats = self._measure_across_levels('requests_list', '/api/requests/?page_size=50')
        self._assert_no_pathological_degradation(stats)

    def test_analysis_load(self):
        _record('--- GET /api/analysis/ ---')
        stats = self._measure_across_levels('analysis', f'/api/analysis/?region={self.region.id}')
        self._assert_no_pathological_degradation(stats)

    def test_buildings_list_load(self):
        _record('--- GET /api/buildings/ ---')
        stats = self._measure_across_levels('buildings_list', f'/api/buildings/?region={self.region.id}')
        self._assert_no_pathological_degradation(stats)

    def _assert_no_pathological_degradation(self, all_stats):
        """
        Not a strict SLA - this local environment's absolute latency
        numbers are not representative of production (see audit report
        §7/§8). What IS a meaningful local signal: every request at every
        concurrency level tested must still SUCCEED (no dropped
        connections, no unhandled 500s, no request-level exceptions), and
        mean latency at the highest level (20) must not blow up by an
        order of magnitude relative to 1 concurrent client - a
        much-larger-than-linear degradation would indicate a real
        contention problem (e.g. serialized locking, connection
        exhaustion) rather than ordinary, expected linear cost.
        """
        for s in all_stats:
            self.assertEqual(s['failure'], 0, f'{s["label"]} @ N={s["concurrency"]}: {s["failure"]} failed requests')
            self.assertEqual(s['exceptions'], [], f'{s["label"]} @ N={s["concurrency"]}: connection exceptions')

        by_n = {s['concurrency']: s for s in all_stats}
        if 1 in by_n and 20 in by_n and by_n[1]['latency_mean_ms'] > 0:
            ratio = by_n[20]['latency_mean_ms'] / by_n[1]['latency_mean_ms']
            _record(f'    mean_latency_ratio (N=20 / N=1): {ratio:.1f}x')
            self.assertLess(
                ratio, 25,
                'mean latency at 20 concurrent clients is disproportionately worse than at 1 '
                '(possible serialization/contention issue, not just expected linear cost)',
            )
