"""
Report/export (backend/api/report_exports.py) performance + correctness
regression tests for the Group 1 implementation phase fixes G1-19 and
G1-20.

- G1-20: generate_capacity_report() now calls _load_data(include_students=False)
  since it only ever reads d['all_beds']/d['occupied_bed_ids'] - the
  Student + active-BedAssignment fetch (and its 5 Python-side category
  list comprehensions) _load_data() used to always perform is skipped
  entirely for this one report. dormify_report/student_actions_report/
  manual_review_report all keep the include_students=True default,
  unchanged.
- G1-19: generate_manual_review_report() now computes _student_issues()
  once per student, in a single shared pass
  (_compute_student_issues()), and reuses that result for the 3 sheets
  that need it (summary counts, full exceptions list, unassigned-with-
  issues) instead of each independently re-running the same per-student
  validation logic with its own fresh seen_ids. The 2 structurally
  different builders (duplicate-ID grouping, missing-data-only check)
  are left as their own separate passes.

Both changes are verified to produce byte-for-byte identical workbook
CONTENTS to the original (pre-consolidation) logic - the tests parse the
generated .xlsx directly via openpyxl (already a project dependency, used
by report_exports.py itself) rather than re-deriving expected values from
the same helper functions being tested.

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_reports_performance -v 2
"""

import time
from pathlib import Path

import openpyxl
from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from django.utils import timezone

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment,
)
from api.report_exports import generate_capacity_report, generate_manual_review_report

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_REPORTS_AFTER_QUERY_COUNTS.txt'


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


def _sheet_rows(ws):
    """(header_row, [data_row, ...]) as plain tuples, from an openpyxl worksheet."""
    rows = list(ws.iter_rows(values_only=True))
    return (rows[0] if rows else None), rows[1:]


class CapacityReportPerformanceTests(TestCase):
    """G1-20: capacity_report must not query Student data at all."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Reports (capacity_report, manual_review_report) — Group 1 POST-FIX query-count evidence',
            'Generated by backend/api/performance_tests/test_reports_performance.py',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='g1-cap-region', name='Group1 Capacity Region')
        self.dorm_type = DormType.objects.create(code=990, name='G1CapDormType', region=self.region)
        self.admin = _make_user('g1-cap-admin@test.com', User.Role.CENTRAL_ADMIN)

        building = Building.objects.create(number=1, dorm_type=self.dorm_type)
        apartment = Apartment.objects.create(
            building=building, number='1', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        room = Room.objects.create(apartment=apartment, name='1', capacity=3)
        self.bed1 = Bed.objects.create(room=room, label='B1')
        self.bed2 = Bed.objects.create(room=room, label='B2')
        Bed.objects.create(room=room, label='B3')  # unoccupied
        student = Student.objects.create(
            student_id='CAP-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        BedAssignment.objects.create(student=student, bed=self.bed1, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin)

    def test_capacity_report_skips_student_queries(self):
        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            buffer = generate_capacity_report(region_id=self.region.id, region_name=self.region.name)
            elapsed_ms = (time.perf_counter() - start) * 1000

        student_queries = [
            q for q in ctx.captured_queries if 'from "api_student"' in q['sql'].lower()
        ]
        lines = [
            '--- capacity_report (post-fix) ---',
            f'total_sql_queries: {len(ctx.captured_queries)}',
            f'standalone_student_queries: {len(student_queries)}',
            f'time_ms: {elapsed_ms:.2f}',
            '',
        ]
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))

        self.assertEqual(len(student_queries), 0, 'capacity_report must not query Student at all (G1-20)')

        # Content still correct: 1 of 3 beds occupied (only bed1 has an
        # ACTIVE assignment; bed2/bed3 do not).
        wb = openpyxl.load_workbook(buffer)
        header, rows = _sheet_rows(wb['תפוסה לפי חדרים'])
        self.assertEqual(len(rows), 1)  # one room
        total_idx = header.index('סה"כ מיטות')
        occ_idx = header.index('מיטות תפוסות')
        self.assertEqual(rows[0][total_idx], 3)
        self.assertEqual(rows[0][occ_idx], 1)


class ManualReviewReportCorrectnessTests(TestCase):
    """
    G1-19: the 3 consolidated sheets (summary counts, full exceptions,
    unassigned-with-issues) must contain byte-for-byte the same content
    as the original per-sheet-independent computation - verified by
    parsing the generated workbook directly, with hand-computed expected
    values for a fixture exercising every category _student_issues()
    checks (missing ID, duplicate ID, missing name, missing gender,
    missing housing/dorm-type) plus a clean student and an
    unassigned-but-clean student (must NOT appear in exception sheets).
    """

    def setUp(self):
        self.region = Region.objects.create(id='g1-mrr-region', name='Group1 Manual Review Region')
        self.dorm_type = DormType.objects.create(code=991, name='G1MRRDormType', region=self.region)
        self.admin = _make_user('g1-mrr-admin@test.com', User.Role.CENTRAL_ADMIN)
        building = Building.objects.create(number=1, dorm_type=self.dorm_type)
        apartment = Apartment.objects.create(
            building=building, number='1', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        self.room = Room.objects.create(apartment=apartment, name='1', capacity=10)

    def test_workbook_content_matches_hand_computed_expectations(self):
        # Note: Student.student_id has a real DB-level unique constraint
        # (api_student_student_id_key), so two PERSISTED students can
        # never share a student_id - the 'תעודת זהות כפולה' duplicate-ID
        # path is exercised separately below, at the Python/unit level
        # (test_compute_student_issues_flags_duplicate_ids_in_memory),
        # against in-memory (unsaved) Student objects, which is the only
        # way to construct that state at all.

        # Clean, assigned student - must appear in NO exception sheet.
        clean = Student.objects.create(
            student_id='MRR-CLEAN', first_name='Clean', last_name='Student', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        bed = Bed.objects.create(room=self.room, label='B1')
        BedAssignment.objects.create(student=clean, bed=bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin)

        # Missing gender, unassigned - must appear in exceptions AND
        # unassigned-with-issues.
        Student.objects.create(
            student_id='MRR-NOGENDER', first_name='No', last_name='Gender', gender=None,
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )

        # Missing student_id entirely, unassigned.
        Student.objects.create(
            student_id='', first_name='No', last_name='Id', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )

        buffer = generate_manual_review_report(region_id=self.region.id, region_name=self.region.name)
        wb = openpyxl.load_workbook(buffer)

        # --- summary sheet: hand-computed counts ---
        _, summary_rows = _sheet_rows(wb['תמצית חריגים'])
        summary = {row[0]: row[1] for row in summary_rows if row[0]}
        # Exceptions: missing-gender student + missing-id student = 2
        # records with issues; both unassigned. clean has none.
        self.assertEqual(summary['סה"כ רשומות עם חריגות'], 2)
        self.assertEqual(summary['תעודת זהות כפולה'], 0)
        self.assertEqual(summary['חסר מגדר'], 1)
        self.assertEqual(summary['חסרה תעודת זהות'], 1)
        self.assertEqual(summary['לא משובצים עם בעיה'], 2)

        # --- full exceptions sheet ---
        _, exc_rows = _sheet_rows(wb['חריגים לבדיקה'])
        self.assertEqual(len(exc_rows), 2)

        # --- unassigned-with-issues sheet: both flagged students, since
        # neither is assigned ---
        _, unassigned_rows = _sheet_rows(wb['לא שובצו עם בעיה'])
        self.assertEqual(len(unassigned_rows), 2)

        # --- duplicate-id sheet (untouched pass) - no real duplicates
        # here, so _to_df([]) emits its standard single "no data"
        # placeholder row (pre-existing report_exports.py behavior,
        # unrelated to this phase's changes).
        _, dup_rows = _sheet_rows(wb['תעודות זהות כפולות'])
        self.assertEqual(len(dup_rows), 1)
        self.assertEqual(dup_rows[0][0], 'אין נתונים')

        # --- missing-data sheet (untouched pass) - both flagged students ---
        _, missing_rows = _sheet_rows(wb['נתונים חסרים'])
        self.assertEqual(len(missing_rows), 2)

    def test_compute_student_issues_flags_duplicate_ids_in_memory(self):
        """
        Unit-level test (no DB persistence, since Student.student_id has
        a real unique constraint) proving _compute_student_issues()'s
        single shared-pass consolidation still reproduces the original
        per-call-fresh-seen_ids semantics exactly: only the SECOND+
        occurrence of a repeated student_id is flagged, and each call
        site (summary/all-exceptions/unassigned) reading from the same
        pre-computed list sees the identical result a fresh independent
        pass would have produced.
        """
        from api.report_exports import _compute_student_issues

        first = Student(
            student_id='UNIT-DUP', first_name='A', last_name='One', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE,
        )
        second = Student(
            student_id='UNIT-DUP', first_name='B', last_name='Two', gender='female',
            housing_type=Student.HousingType.SINGLE_FEMALE,
        )
        clean = Student(
            student_id='UNIT-CLEAN', first_name='C', last_name='Three', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE,
        )

        results = _compute_student_issues([first, second, clean])
        (s0, issues0), (s1, issues1), (s2, issues2) = results

        self.assertIs(s0, first)
        self.assertEqual(issues0, [])  # first occurrence - not flagged
        self.assertIs(s1, second)
        self.assertEqual(issues1, ['תעודת זהות כפולה'])  # second occurrence - flagged
        self.assertIs(s2, clean)
        self.assertEqual(issues2, [])
