"""
GET /api/requests/ (StudentRequestViewSet / StudentRequestSerializer)
performance regression + correctness tests.

History:
- Group 1 audit (project-quality/performance/GROUP1_BACKEND_PERFORMANCE_AUDIT.md,
  finding G1-09, §6.2): measured 127 SQL queries for a single 25-row page
  of region_transfer-type requests (2 fixed + 5 per row: current_bed,
  placement_history, destination_regions queried TWICE via two serializer
  fields, and a lazy source_region fetch). That measurement is frozen in
  the audit document itself (no separate per-endpoint baseline evidence
  file was created for it - the audit phase measured via a temporary,
  deleted diagnostic script, per its own methodology).
- This module (Group 1 implementation phase): measures the FIXED code -
  StudentRequestViewSet.get_queryset() now select_related('source_region')
  and prefetch_related('destination_regions', two Prefetch()s for
  student__bed_assignments distinguished by to_attr). Asserts query count
  stays FLAT as request count grows. Writes CURRENT evidence to
  project-quality/performance/evidence/GROUP1_REQUESTS_AFTER_QUERY_COUNTS.txt
  (a distinct file from the frozen baseline).

MEASUREMENT + REGRESSION TEST. The correctness tests in this module
(StudentRequestNPlus1CorrectnessTests) are the primary safety net: they
prove current_bed/placement_history/destination_region_names/
source_region_name return byte-for-byte the same values as the original
per-row query implementation, across active/ended assignments, a
14-assignment history (exercising the top-10 cap and ordering), a
student-less request, and - critically - the approve() action, which
mutates a student's BedAssignment mid-request and must NOT return a
stale, pre-mutation snapshot from the prefetch cache populated by
get_queryset().

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_requests_performance -v 2

Lives in api/performance_tests/ alongside the other endpoint-specific
performance modules. Business-logic/permission/region-scoping tests for
Requests stay in api/tests_requests.py and api/tests_transfer_regions.py,
untouched by this module.
"""

import re
import time
from collections import Counter
from datetime import timedelta
from pathlib import Path

from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from django.utils import timezone
from rest_framework.test import APIClient

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment, StudentRequest,
)

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_REQUESTS_AFTER_QUERY_COUNTS.txt'

_NUMBER_RE = re.compile(r'\d+')


def _shape(sql):
    return _NUMBER_RE.sub('#', sql)


def _summarize(captured_queries):
    shapes = Counter(_shape(q['sql']) for q in captured_queries)
    repeated = {shape: n for shape, n in shapes.items() if n > 1}
    return {'total': len(captured_queries), 'distinct_shapes': len(shapes), 'repeated_shapes': repeated}


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


def _make_room(dorm_type, building_number, capacity=2, category=Apartment.Category.MALE):
    building = Building.objects.create(number=building_number, dorm_type=dorm_type)
    apartment = Apartment.objects.create(
        building=building, number='1', category=category,
        apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
    )
    room = Room.objects.create(apartment=apartment, name='1', capacity=capacity)
    return building, apartment, room


class StudentRequestListPerformanceTests(TestCase):
    """
    Post-optimization performance regression test for GET /api/requests/.
    Asserts query count stays FLAT (independent of N) - the inverse of the
    frozen Group 1 audit baseline (127 queries at N=25, 5 marginal
    queries/row). If this test starts failing because query count scales
    with N again, the N+1 regressed.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Requests API (GET /api/requests/) — Group 1 POST-FIX query-count evidence',
            'Generated by backend/api/performance_tests/test_requests_performance.py',
            'Compare against the frozen audit baseline: 127 queries at N=25 '
            '(project-quality/performance/GROUP1_BACKEND_PERFORMANCE_AUDIT.md, G1-09).',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='perf-req-region', name='Perf Requests Region')
        self.region2 = Region.objects.create(id='perf-req-region2', name='Perf Requests Region 2')
        self.dorm_type = DormType.objects.create(code=960, name='PerfReqDormType', region=self.region)
        self.admin = _make_user('perf-req-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)
        _, _, self.room = _make_room(self.dorm_type, 1, capacity=200)

    def _build_requests(self, n, with_region_transfer_fields=False):
        StudentRequest.objects.all().delete()
        BedAssignment.objects.all().delete()
        Student.objects.all().delete()
        Bed.objects.filter(room=self.room).delete()
        for i in range(n):
            student = Student.objects.create(
                student_id=f'REQPERF-{i}', first_name='F', last_name='L', gender='male',
                housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
            )
            bed = Bed.objects.create(room=self.room, label=f'ReqBed{i}')
            BedAssignment.objects.create(
                student=student, bed=bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
            )
            if with_region_transfer_fields:
                req = StudentRequest.objects.create(
                    request_type=StudentRequest.RequestType.REGION_TRANSFER,
                    reason='perf', requested_by=self.admin, student=student,
                    transfer_scope=StudentRequest.TransferScope.CROSS_REGION,
                    source_region=self.region,
                )
                req.destination_regions.set([self.region2])
            else:
                StudentRequest.objects.create(
                    request_type=StudentRequest.RequestType.OTHER,
                    reason='perf', requested_by=self.admin, student=student,
                )

    def _measure(self, n, label, with_region_transfer_fields=False, page_size=100):
        self._build_requests(n, with_region_transfer_fields=with_region_transfer_fields)

        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            resp = self.client.get('/api/requests/', {'page_size': page_size})
            elapsed_ms = (time.perf_counter() - start) * 1000

        self.assertEqual(resp.status_code, 200, resp.content)
        results = resp.data['results']
        self.assertEqual(len(results), min(n, page_size))

        summary = _summarize(ctx.captured_queries)
        payload_bytes = len(resp.content)

        lines = [
            f'--- {label}: n_requests={n} region_transfer_fields={with_region_transfer_fields} ---',
            f'endpoint: GET /api/requests/?page_size={page_size}',
            f'rows_returned: {len(results)}',
            f'total_sql_queries: {summary["total"]}',
            f'distinct_query_shapes: {summary["distinct_shapes"]}',
            f'server_side_request_time_ms: {elapsed_ms:.2f}',
            f'response_payload_bytes: {payload_bytes}',
            'repeated_query_shapes (occurrence_count x shape, numbers masked as #):',
        ]
        for shape, count in sorted(summary['repeated_shapes'].items(), key=lambda kv: -kv[1]):
            lines.append(f'  x{count}: {shape[:220]}')
        lines.append('')
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))

        return summary['total'], elapsed_ms, payload_bytes

    def test_query_count_flat_across_n_simple_requests(self):
        """
        Core regression check with plain 'other'-type requests (each
        student has one ACTIVE assignment, exercising current_bed +
        placement_history but not destination_regions/source_region):
        query count at N=100 must be essentially the same as at N=1 - the
        defining proof the per-row N+1 is gone.
        """
        results = {}
        for n in (1, 25, 100):
            total, ms, payload = self._measure(n, f'N={n} SIMPLE REQUESTS')
            results[n] = (total, ms, payload)

        q1, q25, q100 = results[1][0], results[25][0], results[100][0]
        marginal_1_25 = (q25 - q1) / (25 - 1)
        marginal_25_100 = (q100 - q25) / (100 - 25)

        summary_lines = [
            '--- SCALING SUMMARY (simple requests, N=1/25/100) ---',
            f'N=1:   total_queries={q1}   time_ms={results[1][1]:.2f}   bytes={results[1][2]}',
            f'N=25:  total_queries={q25}  time_ms={results[25][1]:.2f}  bytes={results[25][2]}',
            f'N=100: total_queries={q100} time_ms={results[100][1]:.2f} bytes={results[100][2]}',
            f'marginal_queries_per_additional_request (1->25): {marginal_1_25:.2f}',
            f'marginal_queries_per_additional_request (25->100): {marginal_25_100:.2f}',
            'Group 1 audit baseline (pre-fix, region_transfer type): 127 total at N=25 (~5.0/row marginal)',
            '',
        ]
        type(self)._evidence_lines.extend(summary_lines)
        print('\n'.join(summary_lines))

        self.assertLessEqual(marginal_1_25, 0.5)
        self.assertLessEqual(marginal_25_100, 0.5)
        self.assertLess(q100, 20)

    def test_query_count_flat_with_region_transfer_fields_matching_audit_scenario(self):
        """
        Directly reproduces the exact scenario the audit measured at 127
        queries (25 region_transfer-type requests, each with a
        source_region and one destination_region) and proves it is now
        flat and small.
        """
        total, ms, payload = self._measure(
            25, 'N=25 REGION_TRANSFER (audit-matching scenario)', with_region_transfer_fields=True,
        )
        summary_lines = [
            '--- AUDIT-SCENARIO COMPARISON ---',
            f'before (frozen audit baseline): 127 total_queries at N=25',
            f'after (this fix):               {total} total_queries at N=25  time_ms={ms:.2f}  bytes={payload}',
            f'reduction: {127 - total} queries ({(127 - total) / 127 * 100:.1f}%)',
            '',
        ]
        type(self)._evidence_lines.extend(summary_lines)
        print('\n'.join(summary_lines))

        self.assertLess(total, 20)


class StudentRequestNPlus1CorrectnessTests(TestCase):
    """
    Correctness protection for the optimized current_bed/placement_history/
    destination_region_names/source_region_name computation
    (StudentRequestViewSet.get_queryset() + StudentRequestSerializer).
    """

    def setUp(self):
        self.region = Region.objects.create(id='perf-req-corr-region', name='Perf Req Correctness Region')
        self.region_b = Region.objects.create(id='perf-req-corr-region-b', name='Perf Req Correctness Region B')
        self.region_c = Region.objects.create(id='perf-req-corr-region-c', name='Perf Req Correctness Region C')
        self.dorm_type = DormType.objects.create(code=961, name='PerfReqCorrDormType', region=self.region)
        self.admin = _make_user('perf-req-corr-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)
        _, _, self.room = _make_room(self.dorm_type, 501, capacity=200)

    def _get_request_row(self, req_id):
        resp = self.client.get('/api/requests/', {'page_size': 100})
        self.assertEqual(resp.status_code, 200, resp.content)
        return next(r for r in resp.data['results'] if r['id'] == req_id)

    def _original_current_bed_label(self, student):
        """Ground truth: the exact original (pre-optimization) query logic."""
        if student is None:
            return None
        assignment = student.bed_assignments.filter(
            status=BedAssignment.Status.ACTIVE,
        ).select_related('bed', 'bed__room').first()
        bed = assignment.bed if assignment else None
        return bed.label if bed else None

    def _original_placement_history(self, student):
        if student is None:
            return []
        assignments = student.bed_assignments.select_related(
            'bed__room__apartment__building',
            'bed__room__apartment__building__dorm_type__region',
        ).order_by('-assigned_at')[:10]
        history = []
        for a in assignments:
            room = a.bed.room
            history.append({
                'region': room.region.name if room.region else None,
                'building': room.apartment.building.number,
                'apartment': room.apartment.number,
                'room': room.name,
                'status': a.status,
                'assigned_at': a.assigned_at,
                'ended_at': a.ended_at,
            })
        return history

    def test_current_bed_and_placement_history_match_original_with_14_assignment_history(self):
        """
        A student with 14 total bed_assignments (13 ENDED at staggered
        assigned_at, 1 ACTIVE most recent) - exercises: current_bed
        returning ONLY the active one; placement_history capping at
        exactly 10, ordered most-recent-first, correctly excluding the 4
        oldest; and byte-for-byte equivalence with the original per-row
        query logic.
        """
        student = Student.objects.create(
            student_id='HIST-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        now = timezone.now()
        beds = []
        for i in range(14):
            bed = Bed.objects.create(room=self.room, label=f'HistBed{i}')
            beds.append(bed)
            is_active = (i == 13)
            assignment = BedAssignment.objects.create(
                student=student, bed=bed,
                status=BedAssignment.Status.ACTIVE if is_active else BedAssignment.Status.ENDED,
                assigned_by=self.admin,
                # An ENDED assignment must have ended_at at creation time -
                # full_clean() (called from BedAssignment.save()) rejects
                # ENDED/CANCELLED rows with no ended_at, so this can't be
                # deferred to the post-creation assigned_at override below.
                ended_at=(None if is_active else now),
            )
            # assigned_at is auto_now_add - override deterministically after
            # creation (auto_now_add only forces a value on INSERT, not on
            # a later .save()), so ordering/cap assertions are exact and
            # not dependent on wall-clock creation speed.
            assignment.assigned_at = now - timedelta(days=(14 - i))
            if not is_active:
                assignment.ended_at = assignment.assigned_at + timedelta(days=1)
            assignment.save(update_fields=['assigned_at', 'ended_at'])

        req = StudentRequest.objects.create(
            request_type=StudentRequest.RequestType.OTHER, reason='hist',
            requested_by=self.admin, student=student,
        )

        row = self._get_request_row(req.id)

        # current_bed: only HistBed13 (index 13, the ACTIVE one) - never an
        # ended assignment, regardless of recency.
        self.assertEqual(row['current_bed'], 'HistBed13')

        # placement_history: exactly 10 entries, most-recent-first =
        # indices 13,12,...,4 (the 4 oldest, indices 0-3, are excluded).
        # All 14 assignments share the same room/building/apartment (only
        # the bed differs, and placement_history doesn't surface the bed
        # label), so the real equivalence proof is the ground-truth ORM
        # cross-check below (status/assigned_at/ended_at, entry-by-entry).
        self.assertEqual(len(row['placement_history']), 10)
        expected = self._original_placement_history(student)
        self.assertEqual(len(expected), 10)

        # Both sides come from DRF's test-client .data, which holds the
        # pre-render Python representation (real datetime objects, not
        # JSON-rendered ISO strings) for a SerializerMethodField that
        # returns plain dicts - so both `row['placement_history']` (via
        # self.client.get(...).data) and `expected` (built directly from
        # the ORM) carry the same datetime type; compare as-is.
        def _normalize(entries):
            return [
                (e['region'], e['building'], e['apartment'], e['room'], e['status'],
                 e['assigned_at'], e['ended_at'])
                for e in entries
            ]

        actual_normalized = _normalize(row['placement_history'])
        self.assertEqual(actual_normalized, _normalize(expected))
        self.assertEqual(row['current_bed'], self._original_current_bed_label(student))

    def test_destination_regions_and_source_region_match_original(self):
        """
        A region_transfer request with source_region set and TWO
        destination_regions - proves both the declared destination_regions
        PrimaryKeyRelatedField and the get_destination_region_names()
        method field return the same, correct set (no longer two
        independent, possibly-inconsistent queries), and source_region_name
        is populated (no longer a lazy-fetch gap).
        """
        student = Student.objects.create(
            student_id='DEST-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        req = StudentRequest.objects.create(
            request_type=StudentRequest.RequestType.REGION_TRANSFER, reason='dest',
            requested_by=self.admin, student=student,
            transfer_scope=StudentRequest.TransferScope.CROSS_REGION,
            source_region=self.region,
        )
        req.destination_regions.set([self.region_b, self.region_c])

        row = self._get_request_row(req.id)

        self.assertEqual(row['source_region_name'], self.region.name)
        self.assertEqual(sorted(row['destination_regions']), sorted([self.region_b.id, self.region_c.id]))
        self.assertEqual(
            sorted(row['destination_region_names']),
            sorted([self.region_b.name, self.region_c.name]),
        )
        # Ground truth cross-check.
        expected_names = sorted(r.name for r in req.destination_regions.all())
        self.assertEqual(sorted(row['destination_region_names']), expected_names)

    def test_request_with_no_student_returns_empty_safely(self):
        """
        An 'other'-type request with no student attached must not crash,
        and must return current_bed=None, placement_history=[] - matching
        the original obj.student_id short-circuit exactly.
        """
        req = StudentRequest.objects.create(
            request_type=StudentRequest.RequestType.OTHER, reason='no student',
            requested_by=self.admin, student=None,
        )
        row = self._get_request_row(req.id)
        self.assertIsNone(row['current_bed'])
        self.assertEqual(row['placement_history'], [])

    def test_approve_response_reflects_new_assignment_not_stale_prefetch(self):
        """
        CRITICAL correctness case: approve() fetches req via
        get_queryset() (so req.student carries the pre-approval prefetch
        caches), then creates a NEW BedAssignment for that same student
        inside the transaction, then serializes req in the response.
        Without the cache-invalidation fix in approve(), current_bed in
        the response would show the OLD (pre-approval) bed, not the one
        just assigned - a real, silent correctness regression the
        optimization must not introduce.
        """
        student = Student.objects.create(
            student_id='APPR-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        old_bed = Bed.objects.create(room=self.room, label='OldBed')
        BedAssignment.objects.create(
            student=student, bed=old_bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
        )
        # End the old assignment so the new room can accept this student
        # (the unique_active_assignment_per_student constraint forbids two
        # simultaneous ACTIVE assignments).
        BedAssignment.objects.filter(student=student, status=BedAssignment.Status.ACTIVE).update(
            status=BedAssignment.Status.ENDED, ended_at=timezone.now(),
        )

        new_bed = Bed.objects.create(room=self.room, label='NewBed')
        req = StudentRequest.objects.create(
            request_type=StudentRequest.RequestType.ROOM, reason='move',
            requested_by=self.admin, student=student, target_room=self.room,
        )

        resp = self.client.put(f'/api/requests/{req.id}/approve/', {'bed_id': new_bed.id}, format='json')
        self.assertEqual(resp.status_code, 200, resp.content)

        returned_current_bed = resp.data['request']['current_bed']
        self.assertEqual(returned_current_bed, 'NewBed')
        self.assertNotEqual(returned_current_bed, 'OldBed')

        # And the placement_history's most recent entry must be the new,
        # just-created assignment (status 'active'), not stale either.
        history = resp.data['request']['placement_history']
        self.assertGreaterEqual(len(history), 1)
        self.assertEqual(history[0]['status'], BedAssignment.Status.ACTIVE)

        # Ground truth: re-fetch fresh from the DB directly and confirm
        # the API response matches reality, not a cached artifact.
        student.refresh_from_db()
        self.assertEqual(self._original_current_bed_label(student), 'NewBed')
