"""
GET /api/transfers/ (TransferViewSet / TransferSerializer) performance
regression + correctness tests.

History:
- Group 1 audit (project-quality/performance/PERFORMANCE_FINAL_REPORT.md,
  finding G1-13): measured `total_queries` scaling linearly with transfer
  count - 101 queries at N=25, 401 at N=100 (marginal cost 4.00
  queries/transfer) - from TransferSerializer reading
  from_room.apartment.building.*, to_room.apartment.building.*, and
  requested_by.region.* one level beyond what
  TransferViewSet.get_queryset() selected. This endpoint is not called by
  the current frontend (TransfersPage.js uses /api/requests/, not
  /api/transfers/ - see the audit's §6.1), but it remains a reachable
  backend API with a confirmed N+1, fixed in this Group 1 implementation
  phase alongside the (unrelated, more severe) Requests fix.
- This module measures the FIXED code: TransferViewSet.get_queryset() now
  select_related()s the full from_room/to_room -> apartment -> building
  chain and requested_by -> region, matching every field
  TransferSerializer actually reads. Asserts query count stays FLAT.

MEASUREMENT + REGRESSION TEST. No pagination was added - /api/transfers/
remains unpaginated (returns a plain JSON array), per the audit's explicit
instruction not to add pagination without proof it won't break an existing
API contract; see project-quality/performance/PERFORMANCE_FINAL_REPORT.md
for the reasoning.

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_transfers_performance -v 2
"""

import re
import time
from collections import Counter
from pathlib import Path

from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from rest_framework.test import APIClient

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Student, Transfer,
)

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_TRANSFERS_AFTER_QUERY_COUNTS.txt'

_NUMBER_RE = re.compile(r'\d+')


def _shape(sql):
    return _NUMBER_RE.sub('#', sql)


def _summarize(captured_queries):
    shapes = Counter(_shape(q['sql']) for q in captured_queries)
    repeated = {shape: n for shape, n in shapes.items() if n > 1}
    return {'total': len(captured_queries), 'distinct_shapes': len(shapes), 'repeated_shapes': repeated}


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


class TransfersListPerformanceTests(TestCase):
    """
    Post-optimization performance regression test for GET /api/transfers/.
    Asserts query count stays FLAT (independent of N) - the inverse of the
    frozen Group 1 audit baseline (marginal cost 4.00 queries/transfer,
    101 at N=25, 401 at N=100).
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Transfers API (GET /api/transfers/) — Group 1 POST-FIX query-count evidence',
            'Generated by backend/api/performance_tests/test_transfers_performance.py',
            'Compare against the frozen audit baseline: 101 queries at N=25, 401 at N=100 '
            '(project-quality/performance/PERFORMANCE_FINAL_REPORT.md, G1-13).',
            'Endpoint remains unpaginated (returns a plain JSON array) - unchanged from before this fix.',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='perf-tr-region', name='Perf Transfers Region')
        self.dorm_type = DormType.objects.create(code=962, name='PerfTrDormType', region=self.region)
        self.admin = _make_user('perf-tr-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)

        self.building = Building.objects.create(number=1, dorm_type=self.dorm_type)
        self.rooms = []
        for a in range(10):
            apartment = Apartment.objects.create(
                building=self.building, number=str(a + 1), category=Apartment.Category.MIXED,
                apartment_type=Apartment.ApartmentType.SINGLE, room_count=2,
            )
            for r in range(2):
                self.rooms.append(Room.objects.create(apartment=apartment, name=str(r + 1), capacity=2))

    def _measure(self, n, label):
        Transfer.objects.all().delete()
        Student.objects.filter(student_id__startswith='TRPERF-').delete()
        for i in range(n):
            student = Student.objects.create(
                student_id=f'TRPERF-{i}', first_name='F', last_name='L', gender='male',
                housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
            )
            from_room = self.rooms[i % len(self.rooms)]
            to_room = self.rooms[(i + 1) % len(self.rooms)]
            Transfer.objects.create(
                student=student, from_room=from_room, to_room=to_room,
                status=Transfer.Status.PENDING, requested_by=self.admin,
            )

        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            resp = self.client.get('/api/transfers/')
            elapsed_ms = (time.perf_counter() - start) * 1000

        self.assertEqual(resp.status_code, 200, resp.content)
        rows = resp.data if isinstance(resp.data, list) else resp.data.get('results', [])
        self.assertEqual(len(rows), n)
        # Endpoint remains unpaginated by design (see module docstring) -
        # response must still be a plain array, not a paginated envelope.
        self.assertIsInstance(resp.data, list)

        summary = _summarize(ctx.captured_queries)
        payload_bytes = len(resp.content)

        lines = [
            f'--- {label}: n_transfers={n} ---',
            'endpoint: GET /api/transfers/',
            f'rows_returned: {len(rows)}',
            f'total_sql_queries: {summary["total"]}',
            f'distinct_query_shapes: {summary["distinct_shapes"]}',
            f'server_side_request_time_ms: {elapsed_ms:.2f}',
            f'response_payload_bytes: {payload_bytes}',
            'repeated_query_shapes (occurrence_count x shape, numbers masked as #):',
        ]
        for shape, count in sorted(summary['repeated_shapes'].items(), key=lambda kv: -kv[1]):
            lines.append(f'  x{count}: {shape[:220]}')
        lines.append('')
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))

        return summary['total'], elapsed_ms, payload_bytes

    def test_query_count_flat_across_n(self):
        results = {}
        for n in (1, 25, 100):
            total, ms, payload = self._measure(n, f'N={n} TRANSFERS')
            results[n] = (total, ms, payload)

        q1, q25, q100 = results[1][0], results[25][0], results[100][0]
        marginal_1_25 = (q25 - q1) / (25 - 1)
        marginal_25_100 = (q100 - q25) / (100 - 25)

        summary_lines = [
            '--- SCALING SUMMARY (N=1/25/100) ---',
            f'N=1:   total_queries={q1}   time_ms={results[1][1]:.2f}   bytes={results[1][2]}',
            f'N=25:  total_queries={q25}  time_ms={results[25][1]:.2f}  bytes={results[25][2]}',
            f'N=100: total_queries={q100} time_ms={results[100][1]:.2f} bytes={results[100][2]}',
            f'marginal_queries_per_additional_transfer (1->25): {marginal_1_25:.2f}',
            f'marginal_queries_per_additional_transfer (25->100): {marginal_25_100:.2f}',
            'Group 1 audit baseline (pre-fix): 101 at N=25, 401 at N=100 (marginal 4.00/transfer)',
            f'reduction at N=100: {401 - q100} queries ({(401 - q100) / 401 * 100:.1f}%)',
            '',
        ]
        type(self)._evidence_lines.extend(summary_lines)
        print('\n'.join(summary_lines))

        self.assertLessEqual(marginal_1_25, 0.5)
        self.assertLessEqual(marginal_25_100, 0.5)
        self.assertLess(q100, 15)


class TransferSerializerCorrectnessTests(TestCase):
    """
    Correctness protection: the newly-select_related fields
    (from_building_number/from_apartment_number,
    to_building_number/to_apartment_number, requested_by_region_name) must
    return byte-for-byte the same values as before - select_related only
    changes how many queries fetch them, never what they contain.
    """

    def setUp(self):
        self.region = Region.objects.create(id='perf-tr-corr-region', name='Perf Transfers Correctness Region')
        self.dorm_type = DormType.objects.create(code=963, name='PerfTrCorrDormType', region=self.region)
        self.admin = _make_user('perf-tr-corr-admin@test.com', User.Role.CENTRAL_ADMIN, self.region)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)

        self.building = Building.objects.create(number=7, dorm_type=self.dorm_type)
        apartment_a = Apartment.objects.create(
            building=self.building, number='A', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        apartment_b = Apartment.objects.create(
            building=self.building, number='B', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        self.from_room = Room.objects.create(apartment=apartment_a, name='FromRoom', capacity=2)
        self.to_room = Room.objects.create(apartment=apartment_b, name='ToRoom', capacity=2)
        self.student = Student.objects.create(
            student_id='TRCORR-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )

    def test_transfer_row_matches_hand_computed_expected_values(self):
        Transfer.objects.create(
            student=self.student, from_room=self.from_room, to_room=self.to_room,
            status=Transfer.Status.PENDING, requested_by=self.admin,
        )
        resp = self.client.get('/api/transfers/')
        self.assertEqual(resp.status_code, 200, resp.content)
        row = resp.data[0]

        self.assertEqual(row['from_building_number'], self.building.number)
        self.assertEqual(row['from_apartment_number'], 'A')
        self.assertEqual(row['to_building_number'], self.building.number)
        self.assertEqual(row['to_apartment_number'], 'B')
        self.assertEqual(row['requested_by_region_name'], self.region.name)
