"""
Targeted verification: StudentRequestSerializer.get_placement_history() /
StudentRequestViewSet.get_queryset()'s prefetched_placement_history_all.

Purpose (Group 1 follow-up, NOT a new optimization pass): the Group 1
implementation fixed the per-row N+1 for placement_history by prefetching
each relevant student's bed_assignments history via a single flat
Prefetch(..., to_attr='prefetched_placement_history_all'). The ORIGINAL
version of that fix used an unbounded queryset (no DB-side LIMIT) and
sliced to the top 10 in Python inside the serializer (`prefetched[:10]`).
That was correct and flat-query-count (see
GROUP1_REQUESTS_AFTER_QUERY_COUNTS.txt), but at stress scale (measured here:
25 requests, each pointing at a distinct student with 100 historical
BedAssignment rows) it loaded 2500 BedAssignment rows into the app server to
serve only 250 (a 10x overfetch), and that ratio grows unboundedly with
each student's lifetime history.

Because the ORM cannot filter on a Window() annotation directly, this was
fixed with a DB-level top-10-per-student bound
(`_top10_bed_assignment_history_qs()` in views.py, a small
ROW_NUMBER()-windowed raw-SQL subquery referenced via
`pk__in=RawSQL(...)`), which this module now confirms loads exactly 10
rows/student (not 100) at the same stress scale, with identical query count
and identical (correct) API output. See
project-quality/performance/GROUP1_PLACEMENT_HISTORY_VERIFICATION.md for the
full writeup (before/after measurements and the decision rationale).

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_placement_history_verification -v 2
"""

import re
import time
from collections import Counter
from datetime import timedelta
from pathlib import Path

from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from django.utils import timezone
from rest_framework.request import Request
from rest_framework.test import APIClient, APIRequestFactory

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment, StudentRequest,
)
from api.views import StudentRequestViewSet

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_PLACEMENT_HISTORY_VERIFICATION_QUERY_COUNTS.txt'

_NUMBER_RE = re.compile(r'\d+')

N_REQUESTS = 25
HISTORY_PER_STUDENT = 100


def _shape(sql):
    return _NUMBER_RE.sub('#', sql)


def _summarize(captured_queries):
    shapes = Counter(_shape(q['sql']) for q in captured_queries)
    repeated = {shape: n for shape, n in shapes.items() if n > 1}
    return {'total': len(captured_queries), 'distinct_shapes': len(shapes), 'repeated_shapes': repeated}


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


class PlacementHistoryVerificationTests(TestCase):
    """
    Builds N_REQUESTS StudentRequest rows, each pointing at a DISTINCT
    student who has HISTORY_PER_STUDENT total BedAssignment rows (99 ENDED +
    1 ACTIVE) - the worst case for the current implementation, since every
    one of the 25 "relevant" students on the page carries a large history.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Placement history verification (GET /api/requests/) - Group 1 follow-up',
            'Generated by backend/api/performance_tests/test_placement_history_verification.py',
            f'Scenario: N_REQUESTS={N_REQUESTS}, HISTORY_PER_STUDENT={HISTORY_PER_STUDENT} '
            '(each of the 25 requests points at a DISTINCT student, each with 100 historical '
            'BedAssignment rows - worst case for the current "prefetch all, slice to 10 in '
            'Python" implementation).',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='perf-hist-region', name='Perf Placement History Region')
        self.dorm_type = DormType.objects.create(code=962, name='PerfHistDormType', region=self.region)
        self.admin = _make_user('perf-hist-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)
        self.building = Building.objects.create(number=701, dorm_type=self.dorm_type)
        self.apartment = Apartment.objects.create(
            building=self.building, number='1', category=Apartment.Category.MALE,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        self.room = Room.objects.create(apartment=self.apartment, name='1', capacity=200)

        self.students = []
        self.expected_history_by_student = {}
        now = timezone.now()
        for s in range(N_REQUESTS):
            student = Student.objects.create(
                student_id=f'HISTVER-{s}', first_name='F', last_name='L', gender='male',
                housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
            )
            self.students.append(student)
            # One bed reused for all of this student's ENDED assignments (no
            # uniqueness restriction on ENDED rows - only ACTIVE is
            # constrained per-bed/per-student), plus one distinct bed for
            # the final ACTIVE assignment.
            ended_bed = Bed.objects.create(room=self.room, label=f'HistEndedBed{s}')
            active_bed = Bed.objects.create(room=self.room, label=f'HistActiveBed{s}')
            assignments = []
            for i in range(HISTORY_PER_STUDENT - 1):
                a = BedAssignment.objects.create(
                    student=student, bed=ended_bed, status=BedAssignment.Status.ENDED,
                    assigned_by=self.admin, ended_at=now,
                )
                a.assigned_at = now - timedelta(days=(HISTORY_PER_STUDENT - i))
                a.ended_at = a.assigned_at + timedelta(hours=1)
                a.save(update_fields=['assigned_at', 'ended_at'])
                assignments.append(a)
            active = BedAssignment.objects.create(
                student=student, bed=active_bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
            )
            active.assigned_at = now - timedelta(days=0)
            active.save(update_fields=['assigned_at'])
            assignments.append(active)
            # Ground truth: top 10 by -assigned_at (matches the serializer's
            # fallback / original query ordering).
            assignments.sort(key=lambda a: a.assigned_at, reverse=True)
            self.expected_history_by_student[student.id] = assignments[:10]

            StudentRequest.objects.create(
                request_type=StudentRequest.RequestType.OTHER, reason='hist-verify',
                requested_by=self.admin, student=student,
            )

    def test_measure_query_count_time_and_rows_loaded(self):
        """
        Hits GET /api/requests/ for the full 25-row page and measures query
        count / time / response size, then separately measures exactly how
        many BedAssignment ROWS get materialized into Python objects by the
        prefetch (by reproducing the viewset's own get_queryset() directly,
        bypassing the API/serializer layer), confirming the DB-level bound
        (_top10_bed_assignment_history_qs()) actually loads only 10 rows
        per relevant student even at this stress scale, not
        HISTORY_PER_STUDENT (100).
        """
        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            resp = self.client.get('/api/requests/', {'page_size': 100})
            elapsed_ms = (time.perf_counter() - start) * 1000

        self.assertEqual(resp.status_code, 200, resp.content)
        results = resp.data['results']
        self.assertEqual(len(results), N_REQUESTS)

        summary = _summarize(ctx.captured_queries)
        payload_bytes = len(resp.content)

        # --- How many BedAssignment objects actually get loaded into
        # Python by the prefetch, vs. how many are actually used (10 per
        # student)? Reproduce get_queryset() directly (no HTTP layer) so we
        # can inspect the materialized to_attr lists.
        factory = APIRequestFactory()
        django_request = factory.get('/api/requests/', {'page_size': 100})
        drf_request = Request(django_request)
        drf_request.user = self.admin
        view = StudentRequestViewSet()
        view.request = drf_request
        view.action = 'list'
        view.format_kwarg = None
        qs = view.get_queryset().filter(student__in=self.students)
        with CaptureQueriesContext(connection) as ctx2:
            objs = list(qs)
            total_loaded = sum(len(o.student.prefetched_placement_history_all) for o in objs)
            total_used = sum(len(o.student.prefetched_placement_history_all[:10]) for o in objs)
        direct_queries = len(ctx2.captured_queries)

        # DB-level bound now in effect: only 10 rows/student should ever be
        # materialized into Python, regardless of HISTORY_PER_STUDENT.
        expected_loaded = N_REQUESTS * 10
        expected_used = N_REQUESTS * 10

        lines = [
            '--- N=25 REQUESTS, 100 HISTORICAL ASSIGNMENTS PER STUDENT (worst case, AFTER DB-level top-10 bound) ---',
            'endpoint: GET /api/requests/?page_size=100',
            f'rows_returned: {len(results)}',
            f'total_sql_queries (HTTP request): {summary["total"]}',
            f'distinct_query_shapes: {summary["distinct_shapes"]}',
            f'server_side_request_time_ms: {elapsed_ms:.2f}',
            f'response_payload_bytes: {payload_bytes}',
            f'direct_get_queryset_sql_queries (bypassing HTTP/serializer): {direct_queries}',
            f'bedassignment_rows_loaded_into_python (DB-bounded to 10/student): {total_loaded}  (expected {expected_loaded}; BEFORE fix this was {N_REQUESTS * HISTORY_PER_STUDENT})',
            f'bedassignment_rows_actually_used_in_response (top 10 per student): {total_used}  (expected {expected_used})',
            f'overfetch_ratio (loaded / used): {total_loaded / total_used:.1f}x  (BEFORE fix: {HISTORY_PER_STUDENT / 10:.1f}x)',
            'repeated_query_shapes (occurrence_count x shape, numbers masked as #):',
        ]
        for shape, count in sorted(summary['repeated_shapes'].items(), key=lambda kv: -kv[1]):
            lines.append(f'  x{count}: {shape[:220]}')
        lines.append('')
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))

        self.assertEqual(total_loaded, expected_loaded)
        self.assertEqual(total_used, expected_used)

    def test_correctness_top_10_per_request_matches_expected(self):
        """
        For every one of the 25 requests, the returned placement_history
        must be EXACTLY the top-10-by-assigned_at-desc entries for that
        student (out of their 100 historical rows) - not a random/wrong
        slice.
        """
        resp = self.client.get('/api/requests/', {'page_size': 100})
        self.assertEqual(resp.status_code, 200, resp.content)
        results = resp.data['results']
        self.assertEqual(len(results), N_REQUESTS)

        for row in results:
            req = StudentRequest.objects.get(id=row['id'])
            student_id = req.student_id
            history = row['placement_history']
            self.assertEqual(len(history), 10, f'student {student_id} did not get exactly 10 entries')

            expected = self.expected_history_by_student[student_id]
            self.assertEqual(len(expected), 10)
            actual_pairs = [(e['status'], e['assigned_at']) for e in history]
            expected_pairs = [(a.status, a.assigned_at) for a in expected]
            self.assertEqual(actual_pairs, expected_pairs, f'mismatch for student {student_id}')

            # Ordering must be strictly most-recent-first.
            assigned_ats = [e['assigned_at'] for e in history]
            self.assertEqual(assigned_ats, sorted(assigned_ats, reverse=True))

            # The single ACTIVE assignment (always the most recent) must be
            # first, and current_bed must reflect it.
            self.assertEqual(history[0]['status'], BedAssignment.Status.ACTIVE)
