"""
GET /api/students/{id}/ (StudentSerializer detail path) performance +
correctness regression tests for the Group 1 implementation phase fixes
G1-15 and G1-16.

- G1-15: current_bed_id/current_bed_label used to each independently call
  obj.current_bed (an uncached @property that runs a fresh BedAssignment
  query), issuing the same query twice per detail/create/update response.
  Now cached on the instance for the duration of one serialization
  (StudentSerializer._current_bed_cached).
- G1-16: StudentViewSet.get_queryset() now select_related()s 'batch' for
  every non-list action, so StudentSerializer.batch_id (source='batch.id')
  no longer issues a lazy per-response query. The list action's queryset
  (and StudentListSerializer, which has no batch_id field) is completely
  unchanged - see the `else:` branch in get_queryset().

Does NOT touch, re-test, or duplicate the already-passing
api/tests_students_performance.py list-endpoint coverage - see this
module's companion run of that exact suite in the Group 1 implementation
report for confirmation the list endpoint remains healthy.

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_student_detail_performance -v 2
"""

import time
from pathlib import Path

from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from rest_framework.test import APIClient

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment, ImportBatch,
)

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_STUDENTS_DETAIL_AFTER_QUERY_COUNTS.txt'


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


class StudentDetailPerformanceTests(TestCase):
    """
    Frozen Group 1 audit baseline (before this phase):
    GET /api/students/{id}/ for a student with one ACTIVE BedAssignment =
    3 total queries (1 student row + 2 IDENTICAL BedAssignment queries)
    (project-quality/performance/GROUP1_BACKEND_PERFORMANCE_AUDIT.md, §7.4).
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Student Detail API (GET /api/students/{id}/) — Group 1 POST-FIX query-count evidence',
            'Generated by backend/api/performance_tests/test_student_detail_performance.py',
            'Compare against the frozen audit baseline: 3 total queries, 2 of them identical '
            '(project-quality/performance/GROUP1_BACKEND_PERFORMANCE_AUDIT.md, §7.4).',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='g1-sd-region', name='Group1 Student Detail Region')
        self.dorm_type = DormType.objects.create(code=981, name='G1SDDormType', region=self.region)
        self.admin = _make_user('g1-sd-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)

        building = Building.objects.create(number=1, dorm_type=self.dorm_type)
        apartment = Apartment.objects.create(
            building=building, number='1', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        self.room = Room.objects.create(apartment=apartment, name='1', capacity=2)
        self.bed = Bed.objects.create(room=self.room, label='B1')
        self.batch = ImportBatch.objects.create(
            uploaded_by=self.admin, filename='g1sd.xlsx', total_students=1,
            status=ImportBatch.Status.COMPLETED,
        )
        self.student = Student.objects.create(
            student_id='G1SD-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
            batch=self.batch,
        )
        BedAssignment.objects.create(
            student=self.student, bed=self.bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
        )

    def test_query_count_after_fix(self):
        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            resp = self.client.get(f'/api/students/{self.student.id}/')
            elapsed_ms = (time.perf_counter() - start) * 1000

        self.assertEqual(resp.status_code, 200, resp.content)
        bedassignment_queries = [q for q in ctx.captured_queries if 'api_bedassignment' in q['sql'].lower()]

        lines = [
            '--- STUDENT DETAIL (post-fix, student with batch + active assignment) ---',
            f'total_sql_queries: {len(ctx.captured_queries)}',
            f'bedassignment_queries: {len(bedassignment_queries)}',
            f'server_side_request_time_ms: {elapsed_ms:.2f}',
            f'response_payload_bytes: {len(resp.content)}',
            '',
        ]
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))

        # Core regression check: exactly ONE BedAssignment query now
        # (was 2 - see G1-15), and batch is select_related (G1-16), so
        # total query count should be lower than the frozen 3-query
        # baseline despite ALSO now covering 'batch' (which the baseline
        # measurement fixture didn't even have set).
        self.assertEqual(len(bedassignment_queries), 1)
        self.assertLessEqual(len(ctx.captured_queries), 2)

    def test_batch_id_present_without_extra_query_when_batch_set(self):
        with CaptureQueriesContext(connection) as ctx:
            resp = self.client.get(f'/api/students/{self.student.id}/')
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertEqual(resp.data['batch_id'], self.batch.id)
        # 'batch' must be JOINed into the single student-fetch query
        # (appearing after "JOIN"), never queried as its own standalone
        # statement (appearing as the leading "FROM" table) - a plain
        # substring check for the table name would wrongly flag the
        # correct JOIN case too, since the table name legitimately
        # appears in that query's SQL text as part of the JOIN clause.
        standalone_batch_queries = [
            q for q in ctx.captured_queries if 'from "api_importbatch"' in q['sql'].lower()
        ]
        self.assertEqual(
            len(standalone_batch_queries), 0,
            'batch should be joined into the main query, not fetched as its own statement',
        )


class StudentDetailCorrectnessTests(TestCase):
    """
    Correctness protection: current_bed_id/current_bed_label must return
    the exact same values as the original (uncached, double-query)
    implementation, across a student with no assignment, one active
    assignment, and an ended-then-reassigned history.
    """

    def setUp(self):
        self.region = Region.objects.create(id='g1-sd-corr-region', name='Group1 SD Correctness Region')
        self.dorm_type = DormType.objects.create(code=982, name='G1SDCorrDormType', region=self.region)
        self.admin = _make_user('g1-sd-corr-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.client = APIClient()
        self.client.force_authenticate(self.admin)
        building = Building.objects.create(number=2, dorm_type=self.dorm_type)
        apartment = Apartment.objects.create(
            building=building, number='1', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        self.room = Room.objects.create(apartment=apartment, name='1', capacity=3)

    def test_unassigned_student_returns_none(self):
        student = Student.objects.create(
            student_id='G1SD-NONE', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        resp = self.client.get(f'/api/students/{student.id}/')
        self.assertEqual(resp.status_code, 200, resp.content)
        self.assertIsNone(resp.data['current_bed_id'])
        self.assertIsNone(resp.data['current_bed_label'])

    def test_assigned_student_matches_original_uncached_property(self):
        student = Student.objects.create(
            student_id='G1SD-ASSIGNED', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        old_bed = Bed.objects.create(room=self.room, label='OldBed')
        # Ended assignment must have ended_at at creation - full_clean().
        from django.utils import timezone
        BedAssignment.objects.create(
            student=student, bed=old_bed, status=BedAssignment.Status.ENDED,
            assigned_by=self.admin, ended_at=timezone.now(),
        )
        new_bed = Bed.objects.create(room=self.room, label='NewBed')
        BedAssignment.objects.create(
            student=student, bed=new_bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin,
        )

        resp = self.client.get(f'/api/students/{student.id}/')
        self.assertEqual(resp.status_code, 200, resp.content)

        # Ground truth: the original property, called directly.
        student.refresh_from_db()
        expected_bed = student.current_bed
        self.assertIsNotNone(expected_bed)
        self.assertEqual(expected_bed.label, 'NewBed')

        self.assertEqual(resp.data['current_bed_id'], expected_bed.id)
        self.assertEqual(resp.data['current_bed_label'], expected_bed.label)
