"""
GET /api/home/ (home_dashboard) performance + correctness regression tests
for the Group 1 implementation phase fixes G1-06 and G1-08.

- G1-08: latest_inbox's queryset now select_related()s 'region' as well as
  'batch' - RegionInboxSerializer.region_name (source='region.name') no
  longer issues a lazy per-request query whenever latest_inbox is not
  None.
- G1-06: the admin/system-wide path's two independent
  RegionInbox.objects.filter(status=X).count() calls are now one grouped
  query.

G1-07 (run_qs evaluated 4 times) was investigated and deliberately left
unchanged - see the inline comment at views.py's "Allocation runs" section
and project-quality/performance/PERFORMANCE_FINAL_REPORT.md
for the full reasoning (no safe consolidation exists without either
weakening has_completed_run's correctness via a bounded window, which the
implementation instructions explicitly forbid, or assuming allocation-app
invariants this phase has no authority to assume).

Run against Django's disposable TEST database (never touches the real
database):

    cd backend
    ENV_FILE=.env.test python manage.py test api.performance_tests.test_home_dashboard_performance -v 2
"""

import time
from pathlib import Path

from django.conf import settings
from django.db import connection
from django.test import TestCase
from django.test.utils import CaptureQueriesContext
from django.utils import timezone
from rest_framework.test import APIClient

from api.models import (
    User, Region, DormType, Building, Apartment, Room, Bed,
    Student, BedAssignment, AllocationRun, ImportBatch, RegionInbox,
)

EVIDENCE_DIR = Path(settings.BASE_DIR).parent / 'project-quality' / 'performance' / 'evidence'
EVIDENCE_FILE = EVIDENCE_DIR / 'GROUP1_HOME_AFTER_QUERY_COUNTS.txt'


def _make_user(email, role, region=None):
    user = User(email=email, username=email, role=role, region=region, first_name='T', last_name='User')
    user.set_password('testpass123')
    user.save()
    return user


class HomeDashboardPerformanceTests(TestCase):
    """
    Measures GET /api/home/ query count after the G1-06/G1-08 fixes.
    Frozen Group 1 audit baseline (before this phase):
    central_admin=17 queries, region_boss=15 queries
    (project-quality/performance/PERFORMANCE_FINAL_REPORT.md, §4).
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls._evidence_lines = [
            'Home Dashboard API (GET /api/home/) — Group 1 POST-FIX query-count evidence',
            'Generated by backend/api/performance_tests/test_home_dashboard_performance.py',
            'Compare against the frozen audit baseline: central_admin=17, region_boss=15 '
            '(project-quality/performance/PERFORMANCE_FINAL_REPORT.md, §4).',
            '',
        ]

    @classmethod
    def tearDownClass(cls):
        EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
        with open(EVIDENCE_FILE, 'w', encoding='utf-8') as f:
            f.write('\n'.join(cls._evidence_lines) + '\n')
        super().tearDownClass()

    def setUp(self):
        self.region = Region.objects.create(id='g1-home-region', name='Group1 Home Region')
        self.dorm_type = DormType.objects.create(code=980, name='G1HomeDormType', region=self.region)
        self.admin = _make_user('g1-home-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.boss = _make_user('g1-home-boss@test.com', User.Role.REGION_BOSS, self.region)

        building = Building.objects.create(number=1, dorm_type=self.dorm_type)
        apartment = Apartment.objects.create(
            building=building, number='1', category=Apartment.Category.MIXED,
            apartment_type=Apartment.ApartmentType.SINGLE, room_count=1,
        )
        room = Room.objects.create(apartment=apartment, name='1', capacity=2)
        bed = Bed.objects.create(room=room, label='B1')
        student = Student.objects.create(
            student_id='HOMEPERF-1', first_name='F', last_name='L', gender='male',
            housing_type=Student.HousingType.SINGLE_MALE, accepted_dorm_type=self.dorm_type,
        )
        BedAssignment.objects.create(student=student, bed=bed, status=BedAssignment.Status.ACTIVE, assigned_by=self.admin)

        AllocationRun.objects.create(region=self.region, run_by=self.admin)

        batch = ImportBatch.objects.create(
            uploaded_by=self.admin, filename='home-perf.xlsx', total_students=1,
            status=ImportBatch.Status.COMPLETED,
        )
        RegionInbox.objects.create(region=self.region, batch=batch, students_count=1, status=RegionInbox.Status.PENDING)

        self.client = APIClient()

    def _measure(self, user, label):
        self.client.force_authenticate(user)
        with CaptureQueriesContext(connection) as ctx:
            start = time.perf_counter()
            resp = self.client.get('/api/home/')
            elapsed_ms = (time.perf_counter() - start) * 1000
        self.assertEqual(resp.status_code, 200, resp.content)

        lines = [
            f'--- {label} ---',
            f'total_sql_queries: {len(ctx.captured_queries)}',
            f'server_side_request_time_ms: {elapsed_ms:.2f}',
            f'response_payload_bytes: {len(resp.content)}',
            '',
        ]
        type(self)._evidence_lines.extend(lines)
        print('\n'.join(lines))
        return len(ctx.captured_queries), elapsed_ms, len(resp.content)

    def test_query_count_after_fix_central_admin(self):
        total, ms, payload = self._measure(self.admin, 'CENTRAL_ADMIN (post-fix)')
        # Frozen baseline was 17; G1-06 removes 1 query on this
        # (region=None) path (2 counts -> 1 groupby). Loose upper bound,
        # not an exact-equality brittle assertion.
        self.assertLessEqual(total, 16)

    def test_query_count_after_fix_region_boss(self):
        total, ms, payload = self._measure(self.boss, 'REGION_BOSS (post-fix)')
        # Frozen baseline was 15; G1-08 doesn't change query COUNT (it
        # extends an existing select_related, not adds a query) - the fix
        # here is eliminating a query that only fires when latest_inbox
        # exists AND is serialized, i.e. it was already implicitly
        # counted in the 15. Assert it does not regress upward.
        self.assertLessEqual(total, 15)


class HomeDashboardG1CorrectnessTests(TestCase):
    """
    Correctness protection for G1-06 and G1-08.
    """

    def setUp(self):
        self.region_a = Region.objects.create(id='g1-home-corr-a', name='Group1 Home Correctness A')
        self.region_b = Region.objects.create(id='g1-home-corr-b', name='Group1 Home Correctness B')
        self.admin = _make_user('g1-home-corr-admin@test.com', User.Role.CENTRAL_ADMIN)
        self.boss_a = _make_user('g1-home-corr-boss-a@test.com', User.Role.REGION_BOSS, self.region_a)
        self.client = APIClient()

    def test_g1_08_latest_inbox_region_name_populated_correctly(self):
        """
        region_boss's latest_inbox.region_name must reflect the real
        region name - proves the added select_related('region') didn't
        change the value, only how many queries fetch it.
        """
        batch = ImportBatch.objects.create(
            uploaded_by=self.admin, filename='g108.xlsx', total_students=1,
            status=ImportBatch.Status.COMPLETED,
        )
        RegionInbox.objects.create(
            region=self.region_a, batch=batch, students_count=1, status=RegionInbox.Status.VIEWED,
            viewed_at=timezone.now(),
        )
        self.client.force_authenticate(self.boss_a)
        resp = self.client.get('/api/home/')
        self.assertEqual(resp.status_code, 200, resp.content)
        latest_inbox = resp.data['process']['latest_inbox']
        self.assertIsNotNone(latest_inbox)
        self.assertEqual(latest_inbox['region_name'], self.region_a.name)

    def test_g1_06_pending_and_viewed_inbox_counts_match_hand_computed_values(self):
        """
        Admin (system-wide, region=None) path: 3 PENDING + 2 VIEWED +
        1 PROCESSED RegionInbox rows across two regions - the consolidated
        groupby must produce the exact same pending_inbox_count=3 the
        original two independent .count() calls would have, surfaced via
        the 'regions-pending-review' attention item's count field and the
        review workflow stage.
        """
        batch = ImportBatch.objects.create(
            uploaded_by=self.admin, filename='g106.xlsx', total_students=1,
            status=ImportBatch.Status.COMPLETED,
        )
        now = timezone.now()
        for region, status_, n in (
            (self.region_a, RegionInbox.Status.PENDING, 2),
            (self.region_b, RegionInbox.Status.PENDING, 1),
            (self.region_a, RegionInbox.Status.VIEWED, 2),
            (self.region_b, RegionInbox.Status.PROCESSED, 1),
        ):
            for _ in range(n):
                extra = {}
                if status_ == RegionInbox.Status.VIEWED:
                    extra['viewed_at'] = now
                elif status_ == RegionInbox.Status.PROCESSED:
                    extra['processed_at'] = now
                RegionInbox.objects.create(
                    region=region, batch=batch, students_count=1, status=status_, **extra,
                )

        # Ground truth: the exact original (pre-consolidation) query logic.
        expected_pending = RegionInbox.objects.filter(status=RegionInbox.Status.PENDING).count()
        expected_viewed = RegionInbox.objects.filter(status=RegionInbox.Status.VIEWED).count()
        self.assertEqual(expected_pending, 3)
        self.assertEqual(expected_viewed, 2)

        self.client.force_authenticate(self.admin)
        resp = self.client.get('/api/home/')
        self.assertEqual(resp.status_code, 200, resp.content)

        review_item = next(
            (item for item in resp.data['attention_items'] if item['id'] == 'regions-pending-review'), None,
        )
        self.assertIsNotNone(review_item)
        self.assertEqual(review_item['count'], expected_pending)

        # 'workflow' is a top-level list of {key, label_he, label_en,
        # status} stage dicts - the review stage is the entry keyed
        # 'data_review'.
        data_review_stage = next(
            (stage for stage in resp.data['workflow'] if stage['key'] == 'data_review'), None,
        )
        self.assertIsNotNone(data_review_stage)
        self.assertEqual(data_review_stage['status'], 'active')
